package com.haidong.webService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-07-20T18:21:11.851+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "n_webservice", 
                  wsdlLocation = "http://192.168.0.14/webservice/n_webservice.asmx?wsdl",
                  targetNamespace = "http://tempurl.org") 
public class NWebservice extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempurl.org", "n_webservice");
    public final static QName NWebserviceSoap12 = new QName("http://tempurl.org", "n_webserviceSoap12");
    public final static QName NWebserviceSoap = new QName("http://tempurl.org", "n_webserviceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.14/webservice/n_webservice.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NWebservice.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.14/webservice/n_webservice.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NWebservice(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NWebservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NWebservice() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public NWebservice(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public NWebservice(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public NWebservice(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns NWebserviceSoap
     */
    @WebEndpoint(name = "n_webserviceSoap12")
    public NWebserviceSoap getNWebserviceSoap12() {
        return super.getPort(NWebserviceSoap12, NWebserviceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NWebserviceSoap
     */
    @WebEndpoint(name = "n_webserviceSoap12")
    public NWebserviceSoap getNWebserviceSoap12(WebServiceFeature... features) {
        return super.getPort(NWebserviceSoap12, NWebserviceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns NWebserviceSoap
     */
    @WebEndpoint(name = "n_webserviceSoap")
    public NWebserviceSoap getNWebserviceSoap() {
        return super.getPort(NWebserviceSoap, NWebserviceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NWebserviceSoap
     */
    @WebEndpoint(name = "n_webserviceSoap")
    public NWebserviceSoap getNWebserviceSoap(WebServiceFeature... features) {
        return super.getPort(NWebserviceSoap, NWebserviceSoap.class, features);
    }

}
