package com.haidong.webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-07-20T18:21:11.750+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://tempurl.org", name = "n_webserviceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface NWebserviceSoap {

    @WebMethod(operationName = "hospital_getdoctorinfo", action = "http://tempurl.org/hospital_getdoctorinfo")
    @RequestWrapper(localName = "hospital_getdoctorinfo", targetNamespace = "http://tempurl.org", className = "org.tempurl.HospitalGetdoctorinfo")
    @ResponseWrapper(localName = "hospital_getdoctorinfoResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.HospitalGetdoctorinfoResponse")
    @WebResult(name = "hospital_getdoctorinfoResult", targetNamespace = "http://tempurl.org")
    public java.lang.String hospitalGetdoctorinfo(
        @WebParam(name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "baseinfo_getoutpatientinfo", action = "http://tempurl.org/baseinfo_getoutpatientinfo")
    @RequestWrapper(localName = "baseinfo_getoutpatientinfo", targetNamespace = "http://tempurl.org", className = "org.tempurl.BaseinfoGetoutpatientinfo")
    @ResponseWrapper(localName = "baseinfo_getoutpatientinfoResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.BaseinfoGetoutpatientinfoResponse")
    @WebResult(name = "baseinfo_getoutpatientinfoResult", targetNamespace = "http://tempurl.org")
    public java.lang.String baseinfoGetoutpatientinfo(
        @WebParam(name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "hospital_getdeptinfo", action = "http://tempurl.org/hospital_getdeptinfo")
    @RequestWrapper(localName = "hospital_getdeptinfo", targetNamespace = "http://tempurl.org", className = "org.tempurl.HospitalGetdeptinfo")
    @ResponseWrapper(localName = "hospital_getdeptinfoResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.HospitalGetdeptinfoResponse")
    @WebResult(name = "hospital_getdeptinfoResult", targetNamespace = "http://tempurl.org")
    public java.lang.String hospitalGetdeptinfo(
        @WebParam(name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "outpatient_getpayinfo", action = "http://tempurl.org/outpatient_getpayinfo")
    @RequestWrapper(localName = "outpatient_getpayinfo", targetNamespace = "http://tempurl.org", className = "org.tempurl.OutpatientGetpayinfo")
    @ResponseWrapper(localName = "outpatient_getpayinfoResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.OutpatientGetpayinfoResponse")
    @WebResult(name = "outpatient_getpayinfoResult", targetNamespace = "http://tempurl.org")
    public java.lang.String outpatientGetpayinfo(
        @WebParam(name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "pacs_getreport", action = "http://tempurl.org/pacs_getreport")
    @RequestWrapper(localName = "pacs_getreport", targetNamespace = "http://tempurl.org", className = "org.tempurl.PacsGetreport")
    @ResponseWrapper(localName = "pacs_getreportResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.PacsGetreportResponse")
    @WebResult(name = "pacs_getreportResult", targetNamespace = "http://tempurl.org")
    public java.lang.String pacsGetreport(
        @WebParam(name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "outpatient_getprescriptioninfo", action = "http://tempurl.org/outpatient_getprescriptioninfo")
    @RequestWrapper(localName = "outpatient_getprescriptioninfo", targetNamespace = "http://tempurl.org", className = "org.tempurl.OutpatientGetprescriptioninfo")
    @ResponseWrapper(localName = "outpatient_getprescriptioninfoResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.OutpatientGetprescriptioninfoResponse")
    @WebResult(name = "outpatient_getprescriptioninfoResult", targetNamespace = "http://tempurl.org")
    public java.lang.String outpatientGetprescriptioninfo(
        @WebParam(name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "baseinfo_getoutpatientvisitpatient", action = "http://tempurl.org/baseinfo_getoutpatientvisitpatient")
    @RequestWrapper(localName = "baseinfo_getoutpatientvisitpatient", targetNamespace = "http://tempurl.org", className = "org.tempurl.BaseinfoGetoutpatientvisitpatient")
    @ResponseWrapper(localName = "baseinfo_getoutpatientvisitpatientResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.BaseinfoGetoutpatientvisitpatientResponse")
    @WebResult(name = "baseinfo_getoutpatientvisitpatientResult", targetNamespace = "http://tempurl.org")
    public java.lang.String baseinfoGetoutpatientvisitpatient(
        @WebParam(name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "pacs_getreportdetail", action = "http://tempurl.org/pacs_getreportdetail")
    @RequestWrapper(localName = "pacs_getreportdetail", targetNamespace = "http://tempurl.org", className = "org.tempurl.PacsGetreportdetail")
    @ResponseWrapper(localName = "pacs_getreportdetailResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.PacsGetreportdetailResponse")
    @WebResult(name = "pacs_getreportdetailResult", targetNamespace = "http://tempurl.org")
    public java.lang.String pacsGetreportdetail(
        @WebParam(name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "user_unbinding", action = "http://tempurl.org/user_unbinding")
    @RequestWrapper(localName = "user_unbinding", targetNamespace = "http://tempurl.org", className = "org.tempurl.UserUnbinding")
    @ResponseWrapper(localName = "user_unbindingResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.UserUnbindingResponse")
    @WebResult(name = "user_unbindingResult", targetNamespace = "http://tempurl.org")
    public java.lang.String userUnbinding(
        @WebParam(name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "outpatient_getpaybillfee", action = "http://tempurl.org/outpatient_getpaybillfee")
    @RequestWrapper(localName = "outpatient_getpaybillfee", targetNamespace = "http://tempurl.org", className = "org.tempurl.OutpatientGetpaybillfee")
    @ResponseWrapper(localName = "outpatient_getpaybillfeeResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.OutpatientGetpaybillfeeResponse")
    @WebResult(name = "outpatient_getpaybillfeeResult", targetNamespace = "http://tempurl.org")
    public java.lang.String outpatientGetpaybillfee(
        @WebParam(name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "outpatient_getcompletedpaydetailinfo", action = "http://tempurl.org/outpatient_getcompletedpaydetailinfo")
    @RequestWrapper(localName = "outpatient_getcompletedpaydetailinfo", targetNamespace = "http://tempurl.org", className = "org.tempurl.OutpatientGetcompletedpaydetailinfo")
    @ResponseWrapper(localName = "outpatient_getcompletedpaydetailinfoResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.OutpatientGetcompletedpaydetailinfoResponse")
    @WebResult(name = "outpatient_getcompletedpaydetailinfoResult", targetNamespace = "http://tempurl.org")
    public java.lang.String outpatientGetcompletedpaydetailinfo(
        @WebParam(name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "outpatient_getprescriptiondetailinfo", action = "http://tempurl.org/outpatient_getprescriptiondetailinfo")
    @RequestWrapper(localName = "outpatient_getprescriptiondetailinfo", targetNamespace = "http://tempurl.org", className = "org.tempurl.OutpatientGetprescriptiondetailinfo")
    @ResponseWrapper(localName = "outpatient_getprescriptiondetailinfoResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.OutpatientGetprescriptiondetailinfoResponse")
    @WebResult(name = "outpatient_getprescriptiondetailinfoResult", targetNamespace = "http://tempurl.org")
    public java.lang.String outpatientGetprescriptiondetailinfo(
        @WebParam(name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "outpatient_getcompletedpayinfo", action = "http://tempurl.org/outpatient_getcompletedpayinfo")
    @RequestWrapper(localName = "outpatient_getcompletedpayinfo", targetNamespace = "http://tempurl.org", className = "org.tempurl.OutpatientGetcompletedpayinfo")
    @ResponseWrapper(localName = "outpatient_getcompletedpayinfoResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.OutpatientGetcompletedpayinfoResponse")
    @WebResult(name = "outpatient_getcompletedpayinfoResult", targetNamespace = "http://tempurl.org")
    public java.lang.String outpatientGetcompletedpayinfo(
        @WebParam(name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "test_return", action = "http://tempurl.org/test_return")
    @RequestWrapper(localName = "test_return", targetNamespace = "http://tempurl.org", className = "org.tempurl.TestReturn")
    @ResponseWrapper(localName = "test_returnResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.TestReturnResponse")
    @WebResult(name = "test_returnResult", targetNamespace = "http://tempurl.org")
    public java.lang.String testReturn(
        @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
        java.lang.String asInput
    );

    @WebMethod(operationName = "user_binding", action = "http://tempurl.org/user_binding")
    @RequestWrapper(localName = "user_binding", targetNamespace = "http://tempurl.org", className = "org.tempurl.UserBinding")
    @ResponseWrapper(localName = "user_bindingResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.UserBindingResponse")
    @WebResult(name = "user_bindingResult", targetNamespace = "http://tempurl.org")
    public java.lang.String userBinding(
        @WebParam(name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "user_getcardinfo", action = "http://tempurl.org/user_getcardinfo")
    @RequestWrapper(localName = "user_getcardinfo", targetNamespace = "http://tempurl.org", className = "org.tempurl.UserGetcardinfo")
    @ResponseWrapper(localName = "user_getcardinfoResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.UserGetcardinfoResponse")
    @WebResult(name = "user_getcardinfoResult", targetNamespace = "http://tempurl.org")
    public java.lang.String userGetcardinfo(
        @WebParam(name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );
}
